export const ADDNEWTOLL = "ADDNEWTOLL";
export const NEWVEHICLEENTRY = "NEWVEHICLEENTRY";
export const FILTERTOLL = "FILTERTOLL";
export const SEARCHVEHICLE = "SEARCHVEHICLE";
export const SEARCHTOLL = "SEARCHTOLL";
